# Generated by Django 5.0.6 on 2024-05-11 06:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mproducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
